name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.10'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
        sudo systemctl start postgresql
        sudo -u postgres createdb test_db
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
    
    - name: Install Redis
      run: |
        sudo apt-get install -y redis-server
        sudo systemctl start redis-server
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # pip install -r requirements-dev.txt
    
    - name: Set up environment variables
      run: |
        echo "TELEGRAM_BOT_TOKEN=test_token" >> $GITHUB_ENV
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV
        echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=test_key" >> $GITHUB_ENV
        echo "OPENWEATHER_API_KEY=test_key" >> $GITHUB_ENV
    
    - name: Run linting
      run: |
        flake8 modules/ config/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 modules/ config/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run type checking
      run: |
        mypy modules/ config/ --ignore-missing-imports
    
    - name: Run security checks
      run: |
        bandit -r modules/ config/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
    
    - name: Initialize test database
      run: |
        python scripts/init_database.py
    
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=modules --cov=config --cov-report=xml --cov-report=html --cov-fail-under=5
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --cov-append --cov=modules --cov=config --cov-report=xml --cov-fail-under=5
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          htmlcov/
          bandit-report.json
          safety-report.json
          coverage.xml



  security-scan:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'